feature-9: correct workflow

diff --git a/.github/workflows/develop-pipeline.yml b/.github/workflows/develop-pipeline.yml
--- a/.github/workflows/develop-pipeline.yml
+++ b/.github/workflows/develop-pipeline.yml
@@ -63,14 +63,22 @@ jobs:
 
     - name: Run program with Valgrind
       working-directory: ${{github.workspace}}/build
-      run: valgrind --leak-check=full --xml=yes --xml-file=prog_valgrind.xml ./bin/client hello
+      run: valgrind --leak-check=full --xml=yes --xml-file=prog_valgrind.xml ./bin/client -hello
 
     - name: Valgrind Memory check for program
       working-directory: ${{github.workspace}}/build
       run: |
-        export xml_file=prog_valgrind.xml
-        echo "sed 's/"/ /g' < $xml_file | grep '</error>' &> /dev/null\nif [ $? == 0 ]; then\n    printf "%s" "$boldred"\n    echo "[  FAILED  ] Some memory checks failed for $xml_file."\n    error=-1\n        exit $error;\nelse\n    echo "[  SUCCESS  ]"\nfi\n" > check-memory.sh
+        echo "sed 's/\"/ /g' < $xml_file | grep '</error>' &> /dev/null" > check-memory.sh
+        echo "if [ $? == 0 ]; then" >> check-memory.sh
+        echo "    printf \"%s\" \"$boldred\"" >> check-memory.sh
+        echo "    echo \"[  FAILED  ] Some memory checks failed for $xml_file.\"" >> check-memory.sh
+        echo "    error=-1" >> check-memory.sh
+        echo "        exit $error;" >> check-memory.sh
+        echo "else" >> check-memory.sh
+        echo "    echo \"[  SUCCESS  ]\"" >> check-memory.sh
+        echo "fi" >> check-memory.sh
         chmod +x check-memory.sh
+        export xml_file=prog_valgrind.xml
         ./check-memory.sh
 
     - name: Run tests with Valgrind
@@ -81,9 +89,17 @@ jobs:
     - name: Valgrind Memory check for test
       working-directory: ${{github.workspace}}/build/test
       run: |
-        export xml_file=unit_tests_valgrind.xml
-        echo "sed 's/"/ /g' < $xml_file | grep '</error>' &> /dev/null\nif [ $? == 0 ]; then\n    printf "%s" "$boldred"\n    echo "[  FAILED  ] Some memory checks failed for $xml_file."\n    error=-1\n        exit $error;\nelse\n    echo "[  SUCCESS  ]"\nfi\n" > check-memory.sh
+        echo "sed 's/\"/ /g' < $xml_file | grep '</error>' &> /dev/null" > check-memory.sh
+        echo "if [ $? == 0 ]; then" >> check-memory.sh
+        echo "    printf \"%s\" \"$boldred\"" >> check-memory.sh
+        echo "    echo \"[  FAILED  ] Some memory checks failed for $xml_file.\"" >> check-memory.sh
+        echo "    error=-1" >> check-memory.sh
+        echo "        exit $error;" >> check-memory.sh
+        echo "else" >> check-memory.sh
+        echo "    echo \"[  SUCCESS  ]\"" >> check-memory.sh
+        echo "fi" >> check-memory.sh
         chmod +x check-memory.sh
+        export xml_file=unit_tests_valgrind.xml
         ./check-memory.sh
       
 
