feature-9: change pipeline to a unique job

diff --git a/.github/workflows/develop-pipeline.yml b/.github/workflows/develop-pipeline.yml
--- a/.github/workflows/develop-pipeline.yml
+++ b/.github/workflows/develop-pipeline.yml
@@ -43,7 +43,10 @@ jobs:
     - uses: actions/checkout@v3
     
     - name: Install tools
-      run: sudo apt install libboost-all-dev
+      run: |
+        sudo apt install libboost-all-dev
+        sudo apt install -y libev-dev
+        sudo apt install valgrind
         
     - name: Configure CMake
       run: |
@@ -54,55 +57,26 @@ jobs:
       working-directory: ${{github.workspace}}/build
       run: cmake --build .
 
-    - name: Upload workspace
-      uses: actions/upload-artifact@v3
-      with:
-        name: workspaceBuild
-        path: ${{github.workspace}}
-
     - name: Tests
       working-directory: ${{github.workspace}}/build/test
       run: ctest --timeout 300
 
-  run-valgrind:
-    needs: linux-release
-    runs-on: ubuntu-latest
+    - name: Run program with Valgrind
+      working-directory: ${{github.workspace}}/build
+      run: valgrind --leak-check=full --xml=yes --xml-file=prog_valgrind.xml ./bin/client hello
 
-    steps:
-      - name: Set up environment
-        run: |
-          sudo apt update
-          sudo apt install -y libev-dev
-          sudo apt install libboost-all-dev
-          mkdir civ
+    - name: Run tests with Valgrind
+      working-directory: ${{github.workspace}}/build
+      run: valgrind --leak-check=full --xml=yes --xml-file=unit_tests_valgrind.xml ./run_test.sh
 
-      - name: Install Valgrind
-        run: |
-          sudo apt install valgrind
-          echo "Valgrind installed"
-
-      - name: Get artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: workspaceBuild
-          path: ${{github.workspace}}/civ
-
-      - name: Run program with Valgrind
-        working-directory: ${{github.workspace}}/civ/build
-        run: valgrind --leak-check=full --xml=yes --xml-file=prog_valgrind.xml ./build/bin/client hello
-
-      - name: Run tests with Valgrind
-        working-directory: ${{github.workspace}}/civ/build
-        run: valgrind --leak-check=full --xml=yes --xml-file=unit_tests_valgrind.xml ./run_test.sh
-
-      - name: Valgrind Memory check
-        working-directory: ${{github.workspace}}/civ/build
-        run: |
-          export xml_file=prog_valgrind.xml
-          echo "sed 's/"/ /g' < $xml_file | grep '</error>' &> /dev/null\nif [ $? == 0 ]; then\n    printf "%s" "$boldred"\n    echo "[  FAILED  ] Some memory checks failed for $xml_file."\n    error=-1\n        exit $error;\nelse\n    echo "[  SUCCESS  ]"\nfi\n" > check-memory.sh
-          chmod +x check-memory.sh
-          ./check-memory.sh
-          export xml_file=unit_tests_valgrind.xml
-          chmod +x check-memory.sh
+    - name: Valgrind Memory check
+      working-directory: ${{github.workspace}}/build
+      run: |
+        export xml_file=prog_valgrind.xml
+        echo "sed 's/"/ /g' < $xml_file | grep '</error>' &> /dev/null\nif [ $? == 0 ]; then\n    printf "%s" "$boldred"\n    echo "[  FAILED  ] Some memory checks failed for $xml_file."\n    error=-1\n        exit $error;\nelse\n    echo "[  SUCCESS  ]"\nfi\n" > check-memory.sh
+        chmod +x check-memory.sh
+        ./check-memory.sh
+        export xml_file=unit_tests_valgrind.xml
+        ./check-memory.sh
       
 
